name: SUPER_IVIM_DC
channels:
  - pytorch
  - defaults
dependencies:
  - joblib=1.1.0
  - matplotlib
  - numpy=1.21.2
  - pandas=1.3.4
  - pip=21.2.2
  - python=3.8.12
  - pytorch=1.10.0
  - scipy=1.7.1
  - seaborn=0.11.2
  - statsmodels=0.13.0
  - torchvision=0.11.1
  - tqdm=4.62.3
  - yaml=0.2.5
  - pip:
    - nibabel==3.2.1
    - pydicom==2.2.2
    - pyyaml==6.0
    - simpleitk==2.1.1
